services:
  odoo:
    build:
      context: .
      dockerfile: prod/Dockerfile
      args:
        ODOO_VERSION: "18"
    image: guatic-odoo:latest
    container_name: guatic-odoo
    restart: unless-stopped
    ports:
      - "8069"
      - "8072"
    volumes:
      - odoo-data:/var/lib/odoo
    environment:
      HOST: ${PGHOST}
      USER: ${PGUSER:-postgres}
      PASSWORD: ${PGPASSWORD}
      DB: ${PGDATABASE:-postgres}
      PORT: ${PGPORT:-5432}

volumes:
  odoo-data:
