
[options]
# =============================================================================
# CONFIGURACIÓN BÁSICA
# =============================================================================
admin_passwd = sfhsdf$%ahsdasd763hkad6723$&&23
db_host = comercial-asertis-db
db_user = odoo18
db_password = odoo18
db_port = 5432

# =============================================================================
# CONFIGURACIÓN DE ADDONS Y DIRECTORIOS
# =============================================================================
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo

# =============================================================================
# CONFIGURACIÓN CRÍTICA PARA QUEUE_JOB
# =============================================================================
server_wide_modules = base,web,queue_job,bus

# =============================================================================
# CONFIGURACIÓN DEL SERVIDOR WEB - CON WEBSOCKETS
# =============================================================================
xmlrpc_port = 8069
#http_interface = 172.18.0.3
proxy_mode = True

# WEBSOCKETS EN ODOO 18 - CONFIGURACIÓN CORRECTA
longpolling_port = 8072
#websocket_port = 8071
# =============================================================================
# CONFIGURACIÓN DE WORKERS CON REDIS
# =============================================================================
workers = 2
max_cron_threads = 1

# =============================================================================
# CONFIGURACIÓN ESPECÍFICA PARA QUEUE_JOB
# =============================================================================
queue_job_channels = root:4,webhook:2

# =============================================================================
# CONFIGURACIÓN DE MEMORIA Y LÍMITES (OPTIMIZADA PARA 4 WORKERS)
# =============================================================================
limit_memory_hard = 1610612736
limit_memory_soft = 1342177280
limit_time_cpu = 600
limit_time_real = 1800
limit_time_real_cron = 3600
limit_request = 8192
db_maxconn = 80

# =============================================================================
# CONFIGURACIÓN DE LOGS
# =============================================================================
#A =============================================================================
# CONFIGURACIÓN DE SEGURIDAD
# =============================================================================
list_db = False
without_demo = True


#dbfilter=heynow
# =============================================================================
# CONFIGURACIÓN ADICIONAL PARA PERFORMANCE
# =============================================================================
# Cache en memoria
#osv_memory_count_limit = 200
#osv_memory_age_limit = 1.0

# Configuración de transacciones
#db_template = template0
#max_http_request_size = 134217728 
